region         = "eu-west-2"
backend-bucket = "dvh-terraform"
backend-key    = "build/airflow/terraform.tfstate"
ami_id         = "ami-007ec828a062d87a5"
instance_type  = "t2.micro"
key_name       = "dvh"
machine_name   = "machine_name"